config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'
  resources  :users, only: [:new, :create]

  resources  :ads, only: [:new, :create]
  
  # login
  resources  :sessions, only: [:new, :create] do
    collection do
      delete '', to: 'sessions#destroy', as: 'delete'
    end
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
    belongs_to :user, foreign_key: 'id_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :ads, foreign_key: 'id_user'

  validates :name, presence: true
  validates :email, format: { with: /\s*@\s*/ }, presence: true, uniqueness: true
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

    before_action :check_user_signed_in

    def new
        @ad = Ad.new
    end

    def create
        @ad = Ad.new(ad_params)
        @ad.id_user = current_user

        if @ad.save
            redirect_to root_path, notice: 'Ad cadastrado'
        else
            render :new
        end
    end

    private 
    def ad_params
        params.require(:ad).permit(:title, :description, :price)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :user_signed_in?

    def user_signed_in?
        current_user.present?    
    end

    def current_user
        @current_user ||= session[:id_user] if session[:id_user]
    end
    

    def check_user_signed_in
        redirect_to root_path, notice: "É necessário estar logado" unless user_signed_in?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def show
        @ads = Ad.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new        
    end

    def create
        user = User.find_by_email(params[:user][:email])
        if user && user.authenticate(params[:user][:password])
            reset_session
            session[:id_user] = user.id
            redirect_to root_path, notice: t('.welcome', name: user.name)
        else
            redirect_to root_path, alert: t('.invalid')
        end
    end

    def destroy
        reset_session
        redirect_to new_session_path, alert: t('.session_finished') 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        
        if @user.save then
            NotificationMailer.welcome(@user.name, @user.email).deliver_later
            redirect_to new_session_path, notice: 'Cadastro Realizado'
        else
            render :new
        end
    end

    private 

    def user_params
        params.require(:user).permit(:email, :password, :name)
    end
end

app/helpers/ad_helper.rb
module AdHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/new.html.erb
<%= form_for @ad do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <div>
        <%= f.label :price %>
        <%= f.text_field :price %>
    </div>
    <div>
        <%= f.submit %>
    </div>
<% end %>

app/views/home/show.html.erb
<h1>Cadastro de Usuário</h1>

<% if user_signed_in? then %>
    Bem Vindo
    <br>
    <%= button_to t('.logout'), delete_sessions_path, method: :delete %>
    <%= link_to "novo anúncio", new_ad_path %>
<% else %>
    <%= link_to 'Registrar', new_user_path %>
    <%= link_to 'Entrar',  new_session_path %>
<% end %>


<% @ads.each do |ad| %>
    <div class'minhaclasse'>
        <%= ad.title %>
        <%= ad.description %>
        <%= ad.price %>
    </div>
<%  end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classificados</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>
      <%= flash.notice %>
      <%= flash.alert %>
    </p>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <p> Falha ao cadastrar </p>
    <%= @user.errors.full_messages.join(', ') %>
<% end %>

<%= form_for @user, url: users_path do |f| %>
    <div>
        <%= f.label :name, "Nome" %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :email, "Email" %>
        <%= f.email_field :email %>
    </div>
    <div>
        <%= f.label :password, "Senha" %>
        <%= f.password_field :password %>      
    </div>

    <div>
        <%= f.submit "Registrar" %>
    </div>
<% end %>